# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/noors/OneDrive/Documents/GitHub/ENEL_400_Oscilly/rtl/.Xil/Vivado-6164-Noor_laptop/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a35tcpg236-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl 
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    rt::set_parameter singleFileBasedDefaultNettype false
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include C:/Xilinx/2025.1/Vivado/data/rsb/busdef {
      C:/Users/noors/OneDrive/Documents/GitHub/ENEL_400_Oscilly/rtl/adc_processing.sv
      C:/Users/noors/OneDrive/Documents/GitHub/ENEL_400_Oscilly/rtl/averager_simple.sv
      C:/Users/noors/OneDrive/Documents/GitHub/ENEL_400_Oscilly/rtl/bin_to_bcd.sv
      C:/Users/noors/OneDrive/Documents/GitHub/ENEL_400_Oscilly/rtl/digit_multiplexor.sv
      C:/Users/noors/OneDrive/Documents/GitHub/ENEL_400_Oscilly/rtl/mux21.sv
      C:/Users/noors/OneDrive/Documents/GitHub/ENEL_400_Oscilly/rtl/pwm.sv
      C:/Users/noors/OneDrive/Documents/GitHub/ENEL_400_Oscilly/rtl/recorder.sv
      C:/Users/noors/OneDrive/Documents/GitHub/ENEL_400_Oscilly/rtl/register.sv
      C:/Users/noors/OneDrive/Documents/GitHub/ENEL_400_Oscilly/rtl/sar.sv
      C:/Users/noors/OneDrive/Documents/GitHub/ENEL_400_Oscilly/rtl/seven_segment_decoder.sv
      C:/Users/noors/OneDrive/Documents/GitHub/ENEL_400_Oscilly/rtl/seven_segment_digit_selector.sv
      C:/Users/noors/OneDrive/Documents/GitHub/ENEL_400_Oscilly/rtl/seven_segment_display_subsystem.sv
      C:/Users/noors/OneDrive/Documents/GitHub/ENEL_400_Oscilly/rtl/synchro.sv
      C:/Users/noors/OneDrive/Documents/GitHub/ENEL_400_Oscilly/rtl/uart_rx.sv
      C:/Users/noors/OneDrive/Documents/GitHub/ENEL_400_Oscilly/rtl/uart_send_16.sv
      C:/Users/noors/OneDrive/Documents/GitHub/ENEL_400_Oscilly/rtl/uart_tx.sv
      {C:/Users/noors/OneDrive/Documents/GitHub/ENEL_400_Oscilly/rtl/module toplevelMVP.sv}
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top toplevelMVP
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/noors/OneDrive/Documents/GitHub/ENEL_400_Oscilly/rtl/.Xil/Vivado-6164-Noor_laptop/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
